"""Add pw and viewmode cols to Coordinator

Revision ID: 2c30c2430965
Revises: f04a1f7cbb98
Create Date: 2024-01-06 10:11:06.978963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c30c2430965'
down_revision = 'f04a1f7cbb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Coordinators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewModePreference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Coordinators', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('viewModePreference')

    # ### end Alembic commands ###
