"""Add role column to Pianist model

Revision ID: 9f923075253e
Revises: fe8a17773fdf
Create Date: 2023-12-18 11:30:33.224956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f923075253e'
down_revision = 'fe8a17773fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pianists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pianists', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
