"""Add relationships and serialize rules

Revision ID: f04a1f7cbb98
Revises: fec7a34ea81a
Create Date: 2023-12-19 11:41:26.426804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04a1f7cbb98'
down_revision = 'fec7a34ea81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pianist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Events_pianist_id_Pianists'), 'Pianists', ['pianist_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_Events_coordinator_id_Coordinators'), 'Coordinators', ['coordinator_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_Events_student_id_Students'), 'Students', ['student_id'], ['id'])

    with op.batch_alter_table('Pianists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Pianists_coordinator_id_Coordinators'), 'Coordinators', ['coordinator_id'], ['id'])

    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Students_coordinator_id_Coordinators'), 'Coordinators', ['coordinator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Students_coordinator_id_Coordinators'), type_='foreignkey')
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('Pianists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Pianists_coordinator_id_Coordinators'), type_='foreignkey')
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Events_student_id_Students'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Events_coordinator_id_Coordinators'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Events_pianist_id_Pianists'), type_='foreignkey')
        batch_op.drop_column('coordinator_id')
        batch_op.drop_column('pianist_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
